# Generated by Django 3.0.5 on 2020-04-30 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operating_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('IP_address', models.CharField(blank=True, max_length=30, null=True)),
                ('MAC_address', models.CharField(blank=True, max_length=30, null=True)),
                ('users_name', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date(mm/dd/yyyy)')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Operating_system')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=30, unique=True, verbose_name='Computer Name')),
                ('IP_address', models.CharField(max_length=30, verbose_name='IP Address')),
                ('MAC_address', models.CharField(max_length=30, verbose_name='MAC Address')),
                ('users_name', models.CharField(max_length=30, verbose_name='User')),
                ('location', models.CharField(max_length=30, verbose_name='Location')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date(mm/dd/yyyy)')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Operating_system')),
            ],
        ),
    ]
